# Generated by Django 3.2 on 2022-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=3, verbose_name=((3, 'Oh yesss...'), (2, 'So so...'), (1, 'Not at all...'))),
        ),
    ]
